# Site settings
title: ONA Mali
email: mali@ona.io
description: > # this means to ignore newlines until "baseurl:"
  ONA Mali
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mali.ona.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
